 @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").Link("CONTINUE SHOPPING")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").Link("Link").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").Link("Link")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebList("categoryListboxContactUs").Select "Headphones" @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebList("categoryListboxContactUs")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebList("productListboxContactUs").Select "Bose SoundLink Around-ear Wireless Headphones II" @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebList("productListboxContactUs")_;_script infofile_;_ZIP::ssf20.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebEdit("emailContactUs").Set "feeederico.rubes@gmail.com" @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebEdit("emailContactUs")_;_script infofile_;_ZIP::ssf21.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebEdit("subjectTextareaContactUs").Set "u" @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebEdit("subjectTextareaContactUs")_;_script infofile_;_ZIP::ssf22.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebButton("send_btnundefined").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebButton("send btnundefined")_;_script infofile_;_ZIP::ssf23.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").WebElement("Thank you for contacting").Check CheckPoint("Thank you for contacting Advantage support._3") @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").WebElement("Thank you for contacting")_;_script infofile_;_ZIP::ssf24.xml_;_
Browser("Advantage Shopping_2").Page("Advantage Shopping").Link("CONTINUE SHOPPING").Click @@ hightlight id_;_Browser("Advantage Shopping 2").Page("Advantage Shopping").Link("CONTINUE SHOPPING")_;_script infofile_;_ZIP::ssf25.xml_;_
